query ActiveOrder {
  activeOrder {
    id
    code
    state
    totalWithTax
    totalQuantity
    lines {
      id
      linePriceWithTax
      quantity
      featuredAsset {
        preview
      }
    }
  }
}
