mutation AddToCart($productVariantId: ID!, $quantity: Int!) {
  addItemToOrder(
    productVariantId: $productVariantId
    quantity: $quantity
  ) {
    ... on Order {
      ...ActiveOrder
    }
    ... on ErrorResult {
      errorCode
      message
    }
  }
}
