fragment ActiveOrder on Order {
  __typename
  id
  code
  state
  totalWithTax
  totalQuantity
  shippingWithTax
  lines {
    id
    unitPriceWithTax
    quantity
    linePriceWithTax
    productVariant {
      id
      name
    }
    featuredAsset {
      id
      preview
    }
  }
}
