query GetTopSellers {
  search(
    input: { take: 8, groupByProduct: true, sort: { price: ASC } }
  ) {
    items {
      productId
      slug
      productAsset {
        id
        preview
      }
      priceWithTax {
        ... on PriceRange {
          min
          max
        }
      }
      productName
    }
  }
}
