fragment Asset on Asset {
  id
  width
  height
  name
  preview
  focalPoint {
    x
    y
  }
}

query GetProductDetail($slug: String!) {
  product(slug: $slug) {
    id
    name
    description
    variants {
      id
      name
      options {
        code
        name
      }
      price
      priceWithTax
      sku
    }
    featuredAsset {
      ...Asset
    }
    assets {
      ...Asset
    }
    collections {
      id
      slug
      breadcrumbs {
        id
        name
        slug
      }
    }
  }
}
