query GetProductDetail($slug: String!) {
  product(slug: $slug) {
    id
    name
    description
    variants {
      ...Variant
    }
    featuredAsset {
      ...Asset
    }
    assets {
      ...Asset
    }
    collections {
      id
      slug
      breadcrumbs {
        id
        name
        slug
      }
    }
  }
}
