query SearchProducts($input: SearchInput!) {
  search(input: $input) {
    items {
      productId
      slug
      productName
      description
      priceWithTax {
        ... on PriceRange {
          min
          max
        }
      }
      productAsset {
        id
        preview
        focalPoint {
          x
          y
        }
      }
    }
    totalItems
    facetValues {
      count
      facetValue {
        id
        name
        facet {
          id
          name
        }
      }
    }
  }
}
