query GetCollections($options: CollectionListOptions) {
  collections(options: $options) {
    items {
      id
      name
      slug
      parent {
        id
        slug
        name
      }
      featuredAsset {
        id
        preview
      }
    }
  }
}
